name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      sh-debug:
        description: "enable debug on install.sh"
        default: "-x"

permissions:
  contents: read

env:
  SH_DEBUG: ${{ github.event_name == 'workflow_dispath' && inputs.sh-debug || '' }}

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dotfiles
        run: bash "${SH_DEBUG}" ./install.sh --force "${{ matrix.force }}"
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test installed files
        run: |
          set -exo pipefail
          test -f "$HOME/.gitignore" && grep -q "${{ github.workspace }}/.gitignore" "$HOME/.gitignore"
          test -f "$HOME/.gitignore_global" && grep -q "${{ github.workspace }}/.gitignore_global" "$HOME/.gitignore_global"
          if [[ "${{ matrix.force }}" == "n" ]]; then
            test -f "$HOME/.docker/config.json" && grep -v -q "${{ github.workspace }}/HOME/.docker/config.json" "$HOME/.docker/config.json"
          else
            test -f "$HOME/.docker/config.json" && grep -q "${{ github.workspace }}/HOME/.docker/config.json" "$HOME/.docker/config.json"
          fi
          test -f "/etc/profile.d/profile_dotfiles_init_aws.sh"
          test -f "/etc/profile.d/profile_dotfiles_init_kubectl.sh"
          test -f "/etc/profile.d/profile_dotfiles_init_kubectx.sh"
