name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dotfiles
        run: bash ./install.sh --force "${{ matrix.force }}"
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test installed files
        run: |
          set -exo pipefail
          # Check if .gitignore_global exists and is a symlink
          if [[ -L "$HOME/.gitignore_global" && "$(readlink -f "$HOME/.gitignore_global")" == "${{ github.workspace }}/.gitignore_global" ]]; then
            echo ".gitignore_global is correctly linked"
          else
            echo "::error::.gitignore_global is missing or not linked correctly" && exit 1
          fi

          # Check if .docker/config.json exists and is a symlink
          if [[ "${{ matrix.force }}" == "n" ]]; then
            if [[ ! -L "$HOME/.docker/config.json" || "$(readlink -f "$HOME/.docker/config.json")" != "${{ github.workspace }}/HOME/.docker/config.json" ]]; then
              echo "config.json is correctly excluded"
            else
              echo "::error::config.json is incorrectly linked" && exit 1
            fi
          else
            if [[ -L "$HOME/.docker/config.json" && "$(readlink -f "$HOME/.docker/config.json")" == "${{ github.workspace }}/HOME/.docker/config.json" ]]; then
              echo "config.json is correctly linked"
            else
              echo "::error::config.json is missing or not linked correctly" && exit 1
            fi
          fi

          # Check if profile scripts exist
          for file in profile_dotfiles_init_aws.sh profile_dotfiles_init_kubectl.sh profile_dotfiles_init_kubectx.sh; do
            if [[ -f "/etc/profile.d/$file" ]]; then
              echo "$file exists"
            else
              echo "::error::$file is missing" && exit 1
            fi
          done
