name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: bash ./install.sh --force ${{ matrix.force }}
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test installed files
        run: |
          set -eo pipefail
          ls -la "$HOME" | grep .gitconfig | grep "${{ github.workspace }}/.gitconfig"
          ls -la "$HOME" | grep .gitignore_global | grep "${{ github.workspace }}/.gitignore_global"
          if [[ "${{ matrix.force }}" == "n" ]]; then
            docker_grep_arg="-v"
          fi
          ls -la "$HOME/.docker" | grep config.json | grep ${docker_grep_arg} "${{ github.workspace }}/HOME/.docker/config.json"

  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      # Runs `shellcheck` command against `bash` shell.
      - name: Bourne Again Shell (bash)
        if: always()
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --norc -ax -s bash
