name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: bash ./install.sh --force ${{ matrix.force }}
      - name: Test installed files
        run: |
          set -eo pipefail
          ls -la "$HOME" | grep .gitconfig | grep "${{ github.workspace }}/dotfiles-linux/dotfiles-linux/.gitconfig"
          ls -la "$HOME" | grep .gitignore_global | grep "${{ github.workspace }}/dotfiles-linux/dotfiles-linux/.gitignore_global"
          if [[ "${{ matrix.force }}" == "y" ]]; then
            ls -la "$HOME/.docker" | grep config.json | grep "${{ github.workspace }}/dotfiles-linux/dotfiles-linux/HOME/.docker/config.json"
          fi

  # shellcheck:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - uses: actions/checkout@v3

  #     # Runs `shellcheck` command against `sh` shell.
  #     - name: Bourne shell (sh)
  #       uses: ludeeus/action-shellcheck@master
  #       env:
  #         SHELLCHECK_OPTS: --norc -ax -s sh

  #     # Runs `shellcheck` command against `bash` shell.
  #     - name: Bourne Again Shell (bash)
  #       if: always()
  #       uses: ludeeus/action-shellcheck@master
  #       env:
  #         SHELLCHECK_OPTS: --norc -ax -s bash
