name: Check
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        force: ["y", "n"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dotfiles
        run: bash ./install.sh --force "${{ matrix.force }}"
      - name: Show "$HOME"
        run: ls -la "$HOME"
      - name: Test installed files
        run: |
          set -exo pipefail
          if find "$HOME/.gitignore" -type f -maxdepth 1; then
            echo "[x] TEST FAILED. .gitignore found."
            exit 1
          fi

          ls -la "$HOME" | grep .gitignore_global | grep "${{ github.workspace }}/.gitignore_global"
          if [[ "${{ matrix.force }}" == "n" ]]; then
            docker_grep_arg="-v"
          fi
          ls -la "$HOME/.docker" | grep config.json | grep ${docker_grep_arg} "${{ github.workspace }}/HOME/.docker/config.json"
          ls -la "/etc/profile.d" | grep profile_dotfiles_init_aws.sh
          ls -la "/etc/profile.d" | grep profile_dotfiles_init_kubectl.sh
          ls -la "/etc/profile.d" | grep profile_dotfiles_init_kubectx.sh
